config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  root to: 'services#index'

  #devise_for :users, path: :neptun, path_names: {sign_in: :login, sing_out: :logout}, controllers: { registrations: 'users/registrations' }
  resources :servers, :groups, :scenarios
  resources :services do
    member do
      get :start
      get :stop
      get :restart
      get :start_scenario
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :users
  end

end

app/models/service.rb
# frozen_string_literal: true

class Service < ApplicationRecord
  belongs_to :server
  belongs_to :group
  belongs_to :user
  has_many :scenario_services
  has_many :scenarios, through: :scenario_services

  validates :name, presence: true
  validates :name, uniqueness: true

  MAX_COLUMNS = 4
  MAX_ROWS_IN_COLUMN = 20

  def self.ordered
    Service.order(:group_id, :id)
  end

  def self.service_columns(size = nil)
    size ||= Service.all.size
    columns_default = size / MAX_ROWS_IN_COLUMN + 1
    columns_default > MAX_COLUMNS ? MAX_COLUMNS : columns_default
  end

  def do_state(ssh)
    send_command(:state.to_s, nil, nil, ssh)
  end

  def send_command(service_attr_name, login, password, ssh = nil)
    begin
      ssh ||= SshService.new(server.name, login, password)
      ssh.send_command_sudo(sudo_name)
      ssh.send_command(path)
      answer = ssh.send_command(read_attribute(service_attr_name)).byteslice(0, 2000).split(/\n/).join('\n')
      ssh.close
      answer
    rescue SocketError => e
      "Error: #{e.message}"
    end
  end
end

app/controllers/services_controller.rb
# frozen_string_literal: true

class ServicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_service, only: %i[show edit update destroy start stop restart]
  before_action :send_command, only: %i[start stop restart]

  def index
    @services = Service.includes(:group).ordered
    @scenarios = Scenario.all
  end

  def show; end

  def new
    @service = Service.new
  end

  def edit; end

  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
    end
  end

  def start; end

  def stop; end

  def restart; end

  def start_scenario
    ScenarioWorker.perform_async(params[:id])
  end

  private

  def send_command
    @answer = @service.send_command(action_name, current_user.ldap_login, current_user.ldap_password)
  end

  def set_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:id, :name, :path, :sudo_name, :group_id, :user_id, :state, :start, :stop, :restart, :server_id, :status)
  end
end

app/helpers/services_helper.rb
# frozen_string_literal: true

module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_with(model: service, local: true) do |form| %>
  <table class="table-sm w-100">
    <tr>
      <td class="w-0"><%= form.label :name, class: "text-white" %></td>
      <td class="w-100"><%= form.text_field :name, class: "w-100"  %></td>
    </tr>
    <tr>
      <td><%= form.label :path, class: "text-white" %></td>
      <td><%= form.text_field :path, class: "w-100" %></td>
    </tr>
    <tr>
      <td><%= form.label :Sudoname, class: "text-white" %></td>
      <td><%= form.text_field :sudo_name, class: "w-100" %></td>
    </tr>
    <tr>
      <td><%= form.label :group, class: "text-white" %></td>
      <td><%= form.collection_select :group_id, Group.all, :id, :name, prompt: true %></td>
    </tr>
    <tr>
      <td><%= form.label :start, class: "text-white" %></td>
      <td><%= form.text_field :start, class: "w-100" %></td>
    </tr>
    <tr>
      <td><%= form.label :stop, class: "text-white" %></td>
      <td><%= form.text_field :stop, class: "w-100" %></td>
    </tr>
    <tr>
      <td><%= form.label :restart, class: "text-white" %></td>
      <td><%= form.text_field :restart, class: "w-100" %></td>
    </tr>
    <tr>
      <td><%= form.label :state, class: "text-white" %></td>
      <td><%= form.text_field :state, class: "w-100" %></td>
    </tr>
    <tr>
      <td><%= form.label :server_id, class: "text-white" %></td>
      <td><%= form.collection_select :server_id, Server.all, :id, :name, prompt: true %></td>
    </tr>
    <tr>
      <td><%= form.label :user_id, class: "text-white" %></td>
      <td><%= form.collection_select :user_id, User.all, :id, :ldap_login, prompt: true %></td>
    </tr>
    <tr>
      <td><%= form.label :status, class: "text-white" %></td>
      <td><%= form.number_field :status %></td>
    </tr>
  </table>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/services/_index.html.slim
table.table.table-sm.bg-light
  thead
    tr
      th Сервер
      th Команда
      th Статус
      th colspan="3"
  tbody.nbc-font
    - spinner = false
    - services.each do |service|
      tr.nbc-tr
        td= service.name
        td
          .btn-group.nbc-bs role="group"
            - btn_disabled = ""
            - btn_disabled = " disabled" if service.start&.empty?
            = link_to "Start", start_service_path(service), remote: true,         \
              class: "btn btn-dark btn-sm nbc-bs" + btn_disabled, style: "background-color: #8B008B;"
            - btn_disabled = ""
            - btn_disabled = " disabled" if service.stop&.empty?
            = link_to "Stop", stop_service_path(service), remote: true,            \
              class: "btn btn-warning btn-sm text-white nbc-bs" + btn_disabled,    \
              style: "background-color: #FF8C00;" , data: { confirm: 'Are you really want stop service?' }
            - btn_disabled = ""
            - btn_disabled = " disabled" if service.restart&.empty?
            = link_to "Restart", stop_service_path(service), remote: true, \
              class: "btn btn-danger btn-sm nbc-bs" + btn_disabled,        \
              data: { confirm: 'Are you really want stop service?' }
        td
          - if spinner
            .spinner-grow.spinner-grow-sm.nbc role="status"
          - else
            .spinner-grow.spinner-grow-sm.nbc-orange role="status"
              span.sr-only Loading...
          - spinner = !spinner
        td
          .btn-group role="group"
            = link_to 'Show', service, class: "btn btn-outline-warning btn-sm nbc-bs"
            = link_to 'Edit', edit_service_path(service), class: "btn btn-outline-warning btn-sm nbc-bs"
            = link_to 'Drop', service, method: :delete, class: "btn btn-outline-warning btn-sm nbc-bs", data: { confirm: 'Are you sure?' }

app/views/services/edit.html.erb
<div class="col col-md-5">
  <h2 id="center" class="card-header"><%= t('.edit_service') %></h2>
  <div class="card text-white nbc">
    <div class="card-body">
      <%= render 'form', service: @service %>
      <br>
      <%= link_to t('.back'), services_path, class: "btn btn-light" %>
    </div>
  </div>
</div>

app/views/services/index.html.slim
textarea.form-control.ssh-answer.nbc-font rows="3"
textarea.form-control.ssh-command.nbc-font rows="1" style=("max-height: 28pt;")
.btn-group.btn-group-toggle data-toggle="buttons" style=("max-height: 28pt; width: 100%;")
  - @scenarios.each do |scenario|
    label.btn
      = link_to(start_scenario_service_path(scenario), remote: true) do
        input#option1.nbc-orange autocomplete="off" checked="checked" name="options" type="radio" /
        = scenario.name
- groups = @services.map { |service| service.group }.uniq
- groups.each do |group|
  span.col.col-6.shadow-lg.p-1.mb-1.bg-white.rounded.align-self-start
    - group_services = @services.map { |service| service if service.group == group }.compact
    h6#center.card-header.text-monospace style=("height:25px; padding-top:4px;")
      = group.name
    = render 'index', services: group_services

app/views/services/new.html.erb
<div class="col col-md-5">
  <h2 id="center" class="card-header"><%= t('.new_server') %></h2>
  <div class="card text-white mb-3 nbc">
    <div class="card-body">
      <%= render 'form', service: @service %>
      <br>
      <%= link_to t('.back'), services_path, class: "btn btn-light" %>
    </div>
  </div>
</div>

app/views/services/restart.js.erb
$('.ssh-command').val('<%= @service.restart %>');
$('.ssh-answer').val('<%= @answer %>')

app/views/services/show.html.erb
<div class="col col-md-5">
  <h2 id="center" class="card-header"><%= @service.name %></h2>
  <div class="card text-white mb-3 nbc">
    <div class="card-body card-text">
      <p>
        <strong>Path:</strong>
        <%= @service.path %>
      </p>
      <p>
        <strong>Service sudoname:</strong>
        <%= @service.sudo_name %>
      </p>
      <p>
        <strong>Group:</strong>
        <%= @service.group.name %>
      </p>
      <p>
        <strong>Start:</strong>
        <%= @service.start %>
      </p>
      <p>
        <strong>Stop:</strong>
        <%= @service.stop %>
      </p>
      <p>
        <strong>Restart:</strong>
        <%= @service.restart %>
      </p>
      <p>
        <strong>Server:</strong>
        <%= @service.server.name %>
      </p>
      <p>
        <strong>Status:</strong>
        <%= @service.status %>
      </p>
      <p>
        <strong>State:</strong>
        <%= @service.state %>
      </p>
      <p>
        <strong>User:</strong>
        <%= @service&.user&.ldap_login %>
      </p>
      <%= link_to t('.edit'), edit_service_path(@service), class: "btn btn-light" %>
      <%= link_to t('.back'), services_path, class: "btn btn-light" %>
    </div>
  </div>
</div>

app/views/services/start.js.erb
$('.ssh-command').val('<%= @service.start %>');
$('.ssh-answer').val('<%= @answer %>')

app/views/services/stop.js.erb
$('.ssh-command').val('<%= @service.stop %>');
$('.ssh-answer').val('<%= @answer %>')