config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  root to: 'services#index'

  #devise_for :users, path: :neptun, path_names: {sign_in: :login, sing_out: :logout}, controllers: { registrations: 'users/registrations' }
  resources :servers, :groups, :scenarios
  resources :services do
    member do
      get :start
      get :stop
      get :restart
      get :start_scenario
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :users
  end

end

app/models/server.rb
# frozen_string_literal: true

class Server < ApplicationRecord
  has_many :services

  validates :name, :ip, presence: true
  validates :name, uniqueness: true
end

app/controllers/servers_controller.rb
# frozen_string_literal: true

class ServersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_server, only: %i[edit update destroy show]

  def index
    @servers = Server.all
  end

  def new
    @server = Server.new
  end

  def edit; end

  def show; end

  def create
    @server = Server.new(server_params)

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @server.update(server_params)
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @server.destroy
    respond_to do |format|
      format.html { redirect_to servers_url, notice: 'Server was successfully destroyed.' }
    end
  end

  private

  def set_server
    @server = Server.find(params[:id])
  end

  def server_params
    params.require(:server).permit(:name, :ip)
  end
end

app/helpers/servers_helper.rb
# frozen_string_literal: true

module ServersHelper
end

app/views/servers/_form.html.erb
<%= form_with(model: server, local: true) do |form| %>
  <% if server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% server.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table class="table-sm w-100">
    <tr>
      <td class="w-0"><%= form.label :Hostname, class: "text-white" %></td>
      <td class="w-100"><%= form.text_field :name, class: "w-100" %></td>
    </tr>
    <tr>
      <td><%= form.label :ip, class: "text-white" %></td>
      <td><%= form.text_field :ip, class: "w-100" %></td>
    </tr>
  </table>
  </br>
  <div class="actions" >
    <%= form.submit %>
  </div>
<% end %>

app/views/servers/edit.html.erb
<div class="col col-md-5">
  <h2 id="center" class="card-header"><%= t('.edit_server') %></h2>
  <div class="card text-white mb-3 nbc">
    <div class="card-body">
      <%= render 'form', server: @server %>
      <br>
      <%= link_to t('.back'), servers_path, class: "btn btn-light" %>
    </div>
  </div>
</div>

app/views/servers/index.html.erb
<div class="col col-md-5">
  <h2 id="center" class="card-header"><%= t('.servers') %></h2>
  <div class="card text-white mb-3 nbc">
    <div class="card-body">
      <table class="table-sm text-white">
        <thead>
          <tr>
            <th>Host name</th>
            <th>Ip</th>
            <th colspan="2"></th>
          </tr>
        </thead>

        <tbody>
          <% @servers.each do |server| %>
            <tr>
              <td><%= server.name %></td>
              <td><%= server.ip %></td>
              <td><%= link_to t('.edit'), edit_server_path(server), class: "btn btn-light" %></td>
              <td><%= link_to t('.destroy'), server, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-light" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= link_to t('.new_server'), new_server_path, class: "btn btn-light"%>
      <%= link_to t('.back'), :back, class: "btn btn-light" %>
    </div>
  </div>
</div>

app/views/servers/new.html.erb
<div class="col col-md-5">
  <h2 id="center" class="card-header"><%= t('.new_server') %></h2>
  <div class="card text-white mb-3 nbc">
    <div class="card-body">
      <%= render 'form', server: @server %>
      <br>
      <%= link_to t('.back'), servers_path, class: "btn btn-light" %>
    </div>
  </div>
</div>

app/views/servers/show.html.erb
<div class="col col-md-5">
  <h2 id="center" class="card-header"><%= @server.name %></h2>
  <div class="card text-white mb-3 nbc">
    <div class="card-body">
      <p class="card-text">
        <strong>Path:</strong>
        <%= @server.name %>
      </p>

      <p class="card-text">
        <strong>Group:</strong>
        <%= @server.ip %>
      </p>
      <%= link_to 'Edit', edit_server_path(@server), class: "btn btn-light" %>

      <%= link_to t('.back'), servers_path, class: "btn btn-light" %>
    </div>
  </div>
</div>