config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  root to: 'services#index'

  #devise_for :users, path: :neptun, path_names: {sign_in: :login, sing_out: :logout}, controllers: { registrations: 'users/registrations' }
  resources :servers, :groups, :scenarios
  resources :services do
    member do
      get :start
      get :stop
      get :restart
      get :start_scenario
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :users
  end

end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  has_many :services

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: %i[show edit update destroy]

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def edit; end

  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def show; end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :align_left, :position)
  end
end

app/helpers/groups_helper.rb
# frozen_string_literal: true

module GroupsHelper
end

app/views/groups/_form.html.erb
<table class="table-sm text-white">
  <thead>
    <tr>
      <th>Имя группы</th>
      <th>Позиция</th>
      <th>Колонка слева</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.position %></td>
        <td><%= group.align_left %></td>
        <td><%= link_to t('.edit'), edit_group_path(group), class: "btn btn-light" %></td>
        <td><%= link_to t('.destroy'), group, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-light" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/_form_new.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table-sm w-100">
    <tr>
      <td class="w-0"><%= form.label :name, class: "text-white" %></td>
      <td class="w-100"><%= form.text_field :name, class: "w-100" %></td>
    </tr>
    <tr>
      <td><%= form.label :position, class: "text-white" %></td>
      <td><%= form.number_field :position, class: "w-100" %></td>
    </tr>
    <tr>
      <td><%= form.label :alignleft, class: "text-white" %></td>
      <td><%= form.text_field :align_left, class: "w-100" %></td>
    </tr>
  </table>
  <div class="actions" >
    <br>
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class="col col-md-5">
  <h2 id="center" class="card-header"><%= t('.update_group') %></h2>
  <div class="card text-white mb-3 nbc">
    <div class="card-body">
      <%= render 'form_new', group: @group %>
      <br>
      <%= link_to t('.back'), groups_path, class: "btn btn-light" %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="col col-md-5">
  <h2 id="center" class="card-header">Группы</h2>
  <div class="card text-white mb-3 nbc">
    <div class="card-body">
      <%= render 'form', groups: @groups %>
      <br>
      <%= link_to t('.new_group'), new_group_path, class: "btn btn-light" %>
      <br>
      <br>
      <%= link_to t('.back'), :back, class: "btn btn-light" %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="col col-md-5">
  <h2 id="center" class="card-header"><%= t('.new_group') %></h2>
  <div class="card text-white mb-3 nbc">
    <div class="card-body">
      <%= render 'form_new', group: @group %>
      <br>
      <%= link_to t('.back'), groups_path, class: "btn btn-light" %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="col col-md-5">
  <h2 id="center" class="card-header"><%= @group.name %></h2>
  <div class="card text-white mb-3 nbc">
    <div class="card-body">
      <p class="card-text">
        <strong>Path:</strong>
        <%= @group.name %>
      </p>
      <p class="card-text">
        <strong>Position:</strong>
        <%= @group.position %>
      </p>
      <p class="card-text">
        <strong>Align:</strong>
        <%= @group.align_left %>
      </p>
      <%= link_to 'Edit', edit_group_path(@group), class: "btn btn-light" %>

      <%= link_to t('.back'), groups_path, class: "btn btn-light" %>
    </div>
  </div>
</div>