config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  root to: 'services#index'

  #devise_for :users, path: :neptun, path_names: {sign_in: :login, sing_out: :logout}, controllers: { registrations: 'users/registrations' }
  resources :servers, :groups, :scenarios
  resources :services do
    member do
      get :start
      get :stop
      get :restart
      get :start_scenario
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :users
  end

end

app/views/shared/_nav.html.slim
nav.navbar.navbar-dark.fixed-top.nbc
  = link_to t('.neptun'), root_path, class: 'navbar-brand'
  .spinner-grow.text-light role="status" 
  - if user_signed_in?
    = link_to t('.new_service'), new_service_path, class: 'navbar-brand'
    .nav-item.dropdown
      a#navbarDropdown.nav-link.dropdown-toggle.text-light aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
        = t('.manage')
      .dropdown-menu aria-labelledby="navbarDropdown" 
        = link_to t('.dictionaries'), '/admin/dashboard', class: 'dropdown-item'
        .dropdown-divider
        = link_to t('.scenarios'), scenarios_path, class: 'dropdown-item'
        .dropdown-divider
        = link_to t('.jobs'), '/sidekiq', class: 'dropdown-item'
  span.navbar-text
    - if user_signed_in?
      = t('.welcome')
      | ,
      b= current_user.email
      = link_to t('.log_out'), destroy_user_session_path, method: :delete
    - else
      = link_to t('.sign_up'), new_registration_path(resource_name)